default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: event_app_development
  username: event_admin
  password: admin

test:
  <<: *default
  database: event_app_test
  username: event_admin
  password: admin

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).path[1..-1] : 'event_app_production' %>

