default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: event_app_development
  username: event_admin
  password: admin

test:
  <<: *default
  database: event_app_test
  username: event_admin
  password: admin

production:
  <<: *default
  database: event_app_production
  username: <%= ENV["EVENT_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["EVENT_APP_DATABASE_PASSWORD"] %>
