name: "Ruby on Rails CI"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: event_app_test
          POSTGRES_USER: event_admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd="pg_isready -U event_admin"
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://event_admin:admin@localhost:5432/event_app_test
      PGPASSWORD: admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make bin/rails executable
        run: chmod +x bin/rails 

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: |
          ruby -v  # Confirm Ruby version
          bundle install

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -p 5432 -U event_admin; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - name: Prepare test database
        run: |
          echo "Creating and migrating the test database..."
          bundle exec rails db:create db:migrate RAILS_ENV=test
          bundle exec rails db:test:prepare

      - name: Run RSpec tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      - name: Security audit dependencies
        run: bundle exec bundle audit --update

      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      - name: Lint Ruby files
        run: bundle exec rubocop --auto-correct-all --disable-uncorrectable
