name: Deploy to Heroku

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Configure Heroku Authentication
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login heroku" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login heroku" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc
          cat ~/.netrc  # Debugging step - Remove for production

      - name: Add Heroku Git Remote
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote remove heroku || true
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
          git remote -v  # Debugging step

      - name: Debug Authentication
        run: heroku auth:whoami

      - name: Push to Heroku
        run: git push heroku master
